# Permalinks
permalink:        pretty

# Setup
title:            Peak Soccer
tagline:          
url:              https://peak.soccer/
paginate:         1
baseurl:          /
author:
  name:           Phil Wright
  url:            
  email:          
twitter:          
description:      
markdown:         kramdown
kramdown:
  input:          GFM
  smart_quotes:   ["lsquo", "rsquo", "ldquo", "rdquo"]

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/philphantastic/philphantastic.github.io


# Ruby gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# GitHub Metadata
github: [metadata]

# WebBrick headers
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
